-- Unique timestamp preserves the original dependency order for Supabase previews.
alter table public.tutors
  add column if not exists university text,
  add column if not exists university_en text,
  add column if not exists photo_url text,
  add column if not exists banner_url text;

update public.tutors
set
  university = case
    when registry_id = 'P-002' then '서울대학교'
    else '고려대학교'
  end,
  university_en = case
    when registry_id = 'P-002' then 'Seoul National University'
    else 'Korea University'
  end,
  banner_url = case
    when registry_id = 'P-002' then '/university-snu-banner.png'
    else '/university-korea-banner.png'
  end,
  updated_at = now()
where registry_id in ('P-001', 'P-002', 'P-003', 'S-001');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email, full_name)
select
  id,
  coalesce(email, ''),
  nullif(raw_user_meta_data ->> 'full_name', '')
from auth.users
on conflict (id) do update
set
  email = excluded.email,
  full_name = coalesce(public.profiles.full_name, excluded.full_name),
  updated_at = now();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.profiles enable row level security;

revoke all on table public.profiles from anon, authenticated;
grant select on table public.profiles to authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Admins can read profiles" on public.profiles;
create policy "Admins can read profiles"
on public.profiles
for select
to authenticated
using ((select public.is_admin()));

create table if not exists public.portal_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tutor_registry_id text references public.tutors(registry_id) on delete set null,
  session_date date not null,
  starts_at time not null,
  duration_minutes integer not null default 60 check (duration_minutes between 15 and 240),
  subject text not null,
  title text not null,
  session_type text not null default '온라인',
  location text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portal_sessions_user_date_idx
  on public.portal_sessions (user_id, session_date, starts_at);

alter table public.portal_sessions enable row level security;

revoke all on table public.portal_sessions from anon, authenticated;
grant select, insert, update, delete on table public.portal_sessions to authenticated;
grant usage, select on sequence public.portal_sessions_id_seq to authenticated;

drop policy if exists "Users can read their own sessions" on public.portal_sessions;
create policy "Users can read their own sessions"
on public.portal_sessions
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Admins can manage sessions" on public.portal_sessions;
create policy "Admins can manage sessions"
on public.portal_sessions
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

alter table public.tutors enable row level security;

revoke insert, update, delete on table public.tutors from anon;
grant select on table public.tutors to anon, authenticated;
grant insert, update, delete on table public.tutors to authenticated;

drop policy if exists "Admins can read all tutors" on public.tutors;
create policy "Admins can read all tutors"
on public.tutors
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can insert tutors" on public.tutors;
create policy "Admins can insert tutors"
on public.tutors
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins can update tutors" on public.tutors;
create policy "Admins can update tutors"
on public.tutors
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete tutors" on public.tutors;
create policy "Admins can delete tutors"
on public.tutors
for delete
to authenticated
using ((select public.is_admin()));
