-- Admissions-gated accounts, connected-family homework, and tutor credentials.

alter table public.profiles
  add column if not exists account_status text not null default 'approved',
  add column if not exists account_reviewed_at timestamptz;

update public.profiles
set role = 'student'
where role = 'user';

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
    check (role in ('student', 'parent', 'tutor', 'admin'));

alter table public.profiles
  drop constraint if exists profiles_account_status_check;

alter table public.profiles
  add constraint profiles_account_status_check
    check (account_status in ('pending', 'approved', 'rejected'));

-- Existing accounts remain usable. New accounts start in admissions review.
alter table public.profiles
  alter column account_status set default 'pending';

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched_tutor_registry_id text;
  requested_role text;
  initial_status text;
begin
  select registry_id
  into matched_tutor_registry_id
  from public.tutors
  where zoom_host_email is not null
    and lower(zoom_host_email) = lower(coalesce(new.email, ''))
  limit 1;

  requested_role := case
    when new.raw_user_meta_data ->> 'account_role' in ('student', 'parent', 'tutor')
      then new.raw_user_meta_data ->> 'account_role'
    else 'student'
  end;

  initial_status := case
    when coalesce(new.email, '') = 'ssapgoadmin@seonbae.internal' then 'approved'
    else 'pending'
  end;

  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    tutor_registry_id,
    account_status
  )
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    case
      when matched_tutor_registry_id is not null then 'tutor'
      else requested_role
    end,
    matched_tutor_registry_id,
    initial_status
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    role = case
      when public.profiles.role = 'admin' then 'admin'
      when matched_tutor_registry_id is not null then 'tutor'
      else public.profiles.role
    end,
    tutor_registry_id = coalesce(
      matched_tutor_registry_id,
      public.profiles.tutor_registry_id
    ),
    updated_at = now();

  return new;
end;
$$;

create table if not exists public.account_creation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique
    references public.profiles(id) on delete cascade,
  full_name text not null,
  email text not null,
  phone text not null,
  requested_role text not null
    check (requested_role in ('student', 'parent', 'tutor')),
  acceptance_letter_path text not null,
  acceptance_letter_name text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  notification_sent_at timestamptz,
  notification_error text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists account_creation_requests_status_idx
  on public.account_creation_requests (status, created_at desc);

alter table public.account_creation_requests enable row level security;
revoke all on table public.account_creation_requests from public, anon, authenticated;
grant select, update on table public.account_creation_requests to authenticated;

create policy "Applicants can read their account request"
on public.account_creation_requests
for select
to authenticated
using (user_id = (select auth.uid()) or (select public.is_admin()));

create policy "Admins can update account requests"
on public.account_creation_requests
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create table if not exists public.portal_assignments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  tutor_registry_id text not null references public.tutors(registry_id) on delete cascade,
  subject text not null,
  title text not null,
  instructions text not null,
  due_date date not null,
  attachment_name text,
  attachment_path text,
  status text not null default 'todo'
    check (status in ('todo', 'submitted', 'graded')),
  submitted_at timestamptz,
  feedback text,
  graded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portal_assignments_student_due_idx
  on public.portal_assignments (student_id, due_date, status);

create index if not exists portal_assignments_tutor_due_idx
  on public.portal_assignments (tutor_registry_id, due_date, status);

alter table public.portal_assignments enable row level security;
revoke all on table public.portal_assignments from public, anon, authenticated;
grant select, insert, update on table public.portal_assignments to authenticated;
grant usage, select on sequence public.portal_assignments_id_seq to authenticated;

create policy "Students can read their homework"
on public.portal_assignments
for select
to authenticated
using (student_id = (select auth.uid()));

create policy "Parents can read linked student homework"
on public.portal_assignments
for select
to authenticated
using (
  exists (
    select 1
    from public.parent_student_links
    where parent_id = (select auth.uid())
      and student_id = portal_assignments.student_id
  )
);

create policy "Tutors can read assigned homework"
on public.portal_assignments
for select
to authenticated
using (tutor_registry_id = (select public.current_tutor_registry_id()));

create policy "Tutors can assign homework to their students"
on public.portal_assignments
for insert
to authenticated
with check (
  tutor_registry_id = (select public.current_tutor_registry_id())
  and exists (
    select 1
    from public.portal_sessions
    where user_id = portal_assignments.student_id
      and tutor_registry_id = (select public.current_tutor_registry_id())
  )
);

create policy "Tutors can update their homework"
on public.portal_assignments
for update
to authenticated
using (tutor_registry_id = (select public.current_tutor_registry_id()))
with check (tutor_registry_id = (select public.current_tutor_registry_id()));

create policy "Admins can manage homework"
on public.portal_assignments
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create or replace function public.submit_homework(assignment_id bigint)
returns public.portal_assignments
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_assignment public.portal_assignments;
begin
  update public.portal_assignments
  set status = 'submitted', submitted_at = now(), updated_at = now()
  where id = assignment_id
    and student_id = (select auth.uid())
    and status = 'todo'
  returning * into updated_assignment;

  if updated_assignment.id is null then
    raise exception 'Assignment is unavailable for submission.';
  end if;
  return updated_assignment;
end;
$$;

revoke all on function public.submit_homework(bigint) from public;
grant execute on function public.submit_homework(bigint) to authenticated;

create table if not exists public.tutor_credentials (
  id bigint generated by default as identity primary key,
  tutor_id uuid not null references public.profiles(id) on delete cascade,
  tutor_registry_id text references public.tutors(registry_id) on delete set null,
  credential_type text not null
    check (credential_type in ('enrollment', 'degree', 'test_score', 'certificate', 'other')),
  title text not null,
  issuer text not null,
  score text,
  issued_on date,
  proof_name text not null,
  proof_path text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  display_on_profile boolean not null default false,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tutor_credentials_tutor_idx
  on public.tutor_credentials (tutor_id, created_at desc);

alter table public.tutor_credentials enable row level security;
revoke all on table public.tutor_credentials from public, anon, authenticated;
grant select on table public.tutor_credentials to authenticated;

create policy "Tutors can read their credential submissions"
on public.tutor_credentials
for select
to authenticated
using (tutor_id = (select auth.uid()) or (select public.is_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'account-documents',
  'account-documents',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tutor-credentials',
  'tutor-credentials',
  false,
  10485760,
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'homework-files',
  'homework-files',
  false,
  10485760,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

notify pgrst, 'reload schema';
