alter table public.tutors
  add column if not exists zoom_host_email text;

create unique index if not exists tutors_zoom_host_email_unique_idx
  on public.tutors (lower(zoom_host_email))
  where zoom_host_email is not null;

update public.tutors
set
  zoom_host_email = case registry_id
    when 'P-002' then 'seungyun@seonbaetutor.com'
    when 'P-003' then 'byeongguk@seonbaetutor.com'
    when 'S-001' then 'yoonjae@seonbae.com'
    else zoom_host_email
  end,
  updated_at = now()
where registry_id in ('P-002', 'P-003', 'S-001');

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
    check (role in ('user', 'tutor', 'admin')),
  add column if not exists tutor_registry_id text
    references public.tutors(registry_id) on delete set null;

create index if not exists profiles_tutor_registry_idx
  on public.profiles (tutor_registry_id)
  where tutor_registry_id is not null;

update public.profiles as profile
set
  role = case when profile.role = 'admin' then 'admin' else 'tutor' end,
  tutor_registry_id = tutor.registry_id,
  updated_at = now()
from public.tutors as tutor
where tutor.zoom_host_email is not null
  and lower(profile.email) = lower(tutor.zoom_host_email);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  matched_tutor_registry_id text;
begin
  select registry_id
  into matched_tutor_registry_id
  from public.tutors
  where zoom_host_email is not null
    and lower(zoom_host_email) = lower(coalesce(new.email, ''))
  limit 1;

  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    tutor_registry_id
  )
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    case when matched_tutor_registry_id is null then 'user' else 'tutor' end,
    matched_tutor_registry_id
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(public.profiles.full_name, excluded.full_name),
    role = case
      when public.profiles.role = 'admin' then 'admin'
      when matched_tutor_registry_id is not null then 'tutor'
      else public.profiles.role
    end,
    tutor_registry_id = coalesce(
      matched_tutor_registry_id,
      public.profiles.tutor_registry_id
    ),
    updated_at = now();

  return new;
end;
$$;

grant update on table public.profiles to authenticated;

drop policy if exists "Admins can update profiles" on public.profiles;
create policy "Admins can update profiles"
on public.profiles
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

alter table public.portal_sessions
  add column if not exists zoom_meeting_number text,
  add column if not exists zoom_meeting_uuid text,
  add column if not exists zoom_passcode text,
  add column if not exists zoom_host_email text,
  add column if not exists zoom_status text not null default 'unconfigured',
  add column if not exists zoom_created_at timestamptz;

alter table public.portal_sessions
  drop constraint if exists portal_sessions_zoom_status_check;

alter table public.portal_sessions
  add constraint portal_sessions_zoom_status_check
    check (
      zoom_status in (
        'unconfigured',
        'scheduled',
        'live',
        'ended',
        'cancelled'
      )
    );

create unique index if not exists portal_sessions_zoom_meeting_number_idx
  on public.portal_sessions (zoom_meeting_number)
  where zoom_meeting_number is not null;

drop policy if exists "Tutors can read their assigned sessions" on public.portal_sessions;
create policy "Tutors can read their assigned sessions"
on public.portal_sessions
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'tutor'
      and tutor_registry_id = portal_sessions.tutor_registry_id
  )
);

create table if not exists public.zoom_attendance (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  session_id bigint not null
    references public.portal_sessions(id) on delete cascade,
  zoom_participant_id text,
  participant_name text,
  participant_email text,
  joined_at timestamptz,
  left_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists zoom_attendance_session_idx
  on public.zoom_attendance (session_id, joined_at);

alter table public.zoom_attendance enable row level security;

revoke all on table public.zoom_attendance from public, anon, authenticated;
grant select on table public.zoom_attendance to authenticated;

drop policy if exists "Users can read attendance for their sessions" on public.zoom_attendance;
create policy "Users can read attendance for their sessions"
on public.zoom_attendance
for select
to authenticated
using (
  exists (
    select 1
    from public.portal_sessions
    where portal_sessions.id = zoom_attendance.session_id
      and portal_sessions.user_id = (select auth.uid())
  )
);

drop policy if exists "Tutors can read attendance for assigned sessions" on public.zoom_attendance;
create policy "Tutors can read attendance for assigned sessions"
on public.zoom_attendance
for select
to authenticated
using (
  exists (
    select 1
    from public.portal_sessions
    join public.profiles
      on profiles.id = (select auth.uid())
    where portal_sessions.id = zoom_attendance.session_id
      and profiles.role = 'tutor'
      and profiles.tutor_registry_id = portal_sessions.tutor_registry_id
  )
);

drop policy if exists "Admins can read Zoom attendance" on public.zoom_attendance;
create policy "Admins can read Zoom attendance"
on public.zoom_attendance
for select
to authenticated
using ((select public.is_admin()));

notify pgrst, 'reload schema';
