create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_net with schema extensions;

create table if not exists public.account_recovery_email_requests (
  id bigint generated by default as identity primary key,
  lookup_fingerprint text not null,
  requested_at timestamptz not null default now()
);

create index if not exists account_recovery_email_requests_lookup_idx
  on public.account_recovery_email_requests (lookup_fingerprint, requested_at desc);

alter table public.account_recovery_email_requests enable row level security;
revoke all on table public.account_recovery_email_requests from public, anon, authenticated;
revoke all on sequence public.account_recovery_email_requests_id_seq from public, anon, authenticated;

create or replace function public.request_account_id_email(
  p_full_name text,
  p_phone text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  account_email text;
  lookup_key text;
  request_headers jsonb;
  public_api_key text;
begin
  if length(trim(coalesce(p_full_name, ''))) < 2
    or p_phone !~ '^\+[1-9][0-9]{7,14}$'
  then
    return true;
  end if;

  select email
  into account_email
  from public.profiles
  where role = 'user'
    and lower(trim(full_name)) = lower(trim(p_full_name))
    and phone = p_phone
  order by created_at asc
  limit 1;

  if account_email is null then
    return true;
  end if;

  lookup_key := encode(
    extensions.digest(
      convert_to(lower(trim(p_full_name)) || ':' || p_phone, 'utf8'),
      'sha256'
    ),
    'hex'
  );

  if exists (
    select 1
    from public.account_recovery_email_requests
    where lookup_fingerprint = lookup_key
      and requested_at > now() - interval '5 minutes'
  ) then
    return true;
  end if;

  request_headers := coalesce(
    nullif(current_setting('request.headers', true), ''),
    '{}'
  )::jsonb;
  public_api_key := nullif(request_headers ->> 'apikey', '');

  if public_api_key is null then
    raise exception 'API request context is unavailable';
  end if;

  insert into public.account_recovery_email_requests (lookup_fingerprint)
  values (lookup_key);

  delete from public.account_recovery_email_requests
  where requested_at < now() - interval '7 days';

  perform net.http_post(
    url :=
      'https://ccblynvwidadvhtbexfd.supabase.co/auth/v1/otp'
      || '?redirect_to=https%3A%2F%2Fwww.seonbaetutor.com%2Fapi%2Fauth%2Fcallback%3Fnext%3D%2Fportal',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'apikey', public_api_key,
      'Authorization', 'Bearer ' || public_api_key
    ),
    body := jsonb_build_object(
      'email', account_email,
      'create_user', false
    )
  );

  return true;
end;
$$;

revoke all on function public.request_account_id_email(text, text) from public;
revoke all on function public.request_account_id_email(text, text) from anon;
revoke all on function public.request_account_id_email(text, text) from authenticated;
grant execute on function public.request_account_id_email(text, text) to anon, authenticated;

notify pgrst, 'reload schema';
