alter table public.auth_request_limits
  drop constraint if exists auth_request_limits_action_check;

alter table public.auth_request_limits
  add constraint auth_request_limits_action_check
    check (action in ('authenticate', 'signup', 'recovery', 'password_update', 'consultation'));

create or replace function public.consume_auth_request_limit(
  p_key_hash text,
  p_action text,
  p_limit integer,
  p_window_seconds integer
)
returns table (
  allowed boolean,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_count integer;
  current_window_started_at timestamptz;
  window_interval interval;
begin
  if p_key_hash !~ '^[0-9a-f]{64}$'
    or p_action not in ('authenticate', 'signup', 'recovery', 'password_update', 'consultation')
    or p_limit not between 1 and 1000
    or p_window_seconds not between 10 and 86400
  then
    raise exception 'Invalid rate-limit parameters';
  end if;

  window_interval := make_interval(secs => p_window_seconds);

  insert into public.auth_request_limits (
    key_hash,
    action,
    window_started_at,
    request_count,
    updated_at
  )
  values (p_key_hash, p_action, now(), 1, now())
  on conflict (key_hash, action) do update
  set
    window_started_at = case
      when public.auth_request_limits.window_started_at <= now() - window_interval then now()
      else public.auth_request_limits.window_started_at
    end,
    request_count = case
      when public.auth_request_limits.window_started_at <= now() - window_interval then 1
      else public.auth_request_limits.request_count + 1
    end,
    updated_at = now()
  returning
    auth_request_limits.request_count,
    auth_request_limits.window_started_at
  into current_count, current_window_started_at;

  allowed := current_count <= p_limit;
  retry_after_seconds := case
    when allowed then 0
    else greatest(
      1,
      ceil(extract(epoch from (current_window_started_at + window_interval - now())))::integer
    )
  end;

  if random() < 0.01 then
    delete from public.auth_request_limits
    where updated_at < now() - interval '2 days';
  end if;

  return next;
end;
$$;

revoke all on function public.consume_auth_request_limit(
  text,
  text,
  integer,
  integer
) from public, anon, authenticated;

grant execute on function public.consume_auth_request_limit(
  text,
  text,
  integer,
  integer
) to service_role;

create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  name text not null,
  email text not null,
  phone text,
  curriculum text not null,
  preferred_tutor text,
  subject text not null,
  goals text not null,
  language text not null default 'ko'
    check (language in ('ko', 'en')),
  source text not null default 'website'
    check (source in ('website', 'footer')),
  status text not null default 'new'
    check (status in ('new', 'contacted', 'closed')),
  notification_sent_at timestamptz,
  notification_error text,
  handled_by uuid references public.profiles(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint consultation_requests_name_check
    check (char_length(btrim(name)) between 2 and 80),
  constraint consultation_requests_email_check
    check (char_length(btrim(email)) between 3 and 254),
  constraint consultation_requests_phone_check
    check (phone is null or char_length(btrim(phone)) between 5 and 32),
  constraint consultation_requests_curriculum_check
    check (char_length(btrim(curriculum)) between 1 and 80),
  constraint consultation_requests_preferred_tutor_check
    check (preferred_tutor is null or char_length(btrim(preferred_tutor)) between 1 and 80),
  constraint consultation_requests_subject_check
    check (char_length(btrim(subject)) between 1 and 120),
  constraint consultation_requests_goals_check
    check (char_length(btrim(goals)) between 2 and 3000)
);

create index if not exists consultation_requests_status_created_idx
  on public.consultation_requests (status, created_at desc);

alter table public.consultation_requests enable row level security;

revoke all on table public.consultation_requests from public, anon, authenticated;
grant select, update on table public.consultation_requests to authenticated;

create policy "Admins can read consultation requests"
on public.consultation_requests
for select
to authenticated
using ((select public.is_admin()));

create policy "Admins can update consultation requests"
on public.consultation_requests
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

notify pgrst, 'reload schema';
